onEvent('recipes', e => {

    function seedCrafting(base, ingredient, essence, output, time) {
        e.custom({ "type": "naturesaura:tree_ritual", "ingredients": [{ "item": base }, { "item": ingredient }, { "item": ingredient }, { "item": ingredient }, { "item": essence }, { "item": essence }, { "item": essence }, { "item": essence }], "sapling": { "item": "forbidden_arcanus:mysterywood_sapling" }, "output": { "item": output }, "time": time })
    }
    function seedCraftingNBT(base, ingredient, essence, output, time) { e.custom({ "type": "naturesaura:tree_ritual", "ingredients": [{ "item": base }, { "type": "forge:nbt", "item": "mysticalagriculture:soul_jar", "count": 1, "nbt": ingredient }, { "type": "forge:nbt", "item": "mysticalagriculture:soul_jar", "count": 1, "nbt": ingredient }, { "type": "forge:nbt", "item": "mysticalagriculture:soul_jar", "count": 1, "nbt": ingredient }, { "item": essence }, { "item": essence }, { "item": essence }, { "item": essence }], "sapling": { "item": "forbidden_arcanus:mysterywood_sapling" }, "output": { "item": output }, "time": time }) }

    //Elemental
    seedCrafting('mysticalagriculture:prosperity_seed_base', 'mysticalagriculture:air_agglomeratio', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:air_seeds', 40)
    seedCrafting('mysticalagriculture:prosperity_seed_base', 'mysticalagriculture:fire_agglomeratio', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:fire_seeds', 40)
    seedCrafting('mysticalagriculture:prosperity_seed_base', 'mysticalagriculture:water_agglomeratio', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:water_seeds', 40)
    seedCrafting('mysticalagriculture:prosperity_seed_base', 'mysticalagriculture:earth_agglomeratio', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:earth_seeds', 40)
    //Inferium
    seedCrafting('ragnamod_seven:inferium_seed', 'minecraft:stone', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:stone_seeds', 60)
    seedCrafting('ragnamod_seven:inferium_seed', 'minecraft:dirt', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:dirt_seeds', 60)
    seedCrafting('ragnamod_seven:inferium_seed', 'minecraft:oak_log', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:wood_seeds', 60)
    seedCrafting('ragnamod_seven:inferium_seed', 'minecraft:packed_ice', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:ice_seeds', 60)
    seedCrafting('ragnamod_seven:inferium_seed', 'minecraft:deepslate', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:deepslate_seeds', 60)
    //Prudentium
    seedCrafting('ragnamod_seven:prudentium_seed', 'mysticalagriculture:nature_agglomeratio', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:nature_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'mysticalagriculture:dye_agglomeratio', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:dye_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'mysticalagriculture:nether_agglomeratio', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:nether_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'minecraft:coal', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:coal_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'mysticalagriculture:coral_agglomeratio', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:coral_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'mysticalagriculture:honey_agglomeratio', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:honey_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'minecraft:amethyst_shard', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:amethyst_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'integrateddynamics:crystalized_menril_block', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:menril_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'create:limestone', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:limestone_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'mysticalagriculture:mystical_flower_agglomeratio', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:mystical_flower_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'thermal:apatite', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:apatite_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'thermal:niter', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:saltpeter_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'tinkers_reforged:aluminum_ingot', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:aluminum_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'thermal:sulfur', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:sulfur_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'ftbic:silicon', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:silicon_seeds', 80)
    seedCrafting('ragnamod_seven:prudentium_seed', 'ftbic:rubber', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:rubber_seeds', 80)
    seedCraftingNBT('ragnamod_seven:prudentium_seed', '{Souls:8.0d,Type:"mysticalagriculture:pig"}', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:pig_seeds', 80)
    seedCraftingNBT('ragnamod_seven:prudentium_seed', '{Souls:8.0d,Type:"mysticalagriculture:chicken"}', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:chicken_seeds', 80)
    seedCraftingNBT('ragnamod_seven:prudentium_seed', '{Souls:6.0d,Type:"mysticalagriculture:turtle"}', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:turtle_seeds', 80)
    seedCraftingNBT('ragnamod_seven:prudentium_seed', '{Souls:12.0d,Type:"mysticalagriculture:slime"}', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:slime_seeds', 80)
    seedCraftingNBT('ragnamod_seven:prudentium_seed', '{Souls:6.0d,Type:"mysticalagriculture:fish"}', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:fish_seeds', 80)
    seedCraftingNBT('ragnamod_seven:prudentium_seed', '{Souls:6.0d,Type:"mysticalagriculture:squid"}', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:squid_seeds', 80)
    seedCraftingNBT('ragnamod_seven:prudentium_seed', '{Souls:8.0d,Type:"mysticalagriculture:sheep"}', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:sheep_seeds', 80)
    seedCraftingNBT('ragnamod_seven:prudentium_seed', '{Souls:8.0d,Type:"mysticalagriculture:cow"}', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:cow_seeds', 80)
    //Tertium
    seedCrafting('ragnamod_seven:tertium_seed', 'minecraft:iron_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:iron_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'minecraft:copper_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:copper_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'minecraft:quartz', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:nether_quartz_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'minecraft:glowstone_dust', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:glowstone_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'minecraft:redstone', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:redstone_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'minecraft:obsidian', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:obsidian_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'mysticalagriculture:prismarine_agglomeratio', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:prismarine_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'ae2:certus_quartz_crystal', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:certus_quartz_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'ae2:sky_stone_block', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:sky_stone_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'twilightforest:ironwood_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:ironwood_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'twilightforest:steeleaf_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:steeleaf_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'botania:manasteel_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:manasteel_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tconstruct:pig_iron_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:pig_iron_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tconstruct:slimesteel_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:slimesteel_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tconstruct:amethyst_bronze_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:amethyst_bronze_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'thermal:lead_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:lead_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'thermal:silver_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:silver_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'create:brass_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:brass_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'create:zinc_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:zinc_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'thermal:bronze_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:bronze_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'thermal:tin_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:tin_seeds', 100)
    seedCraftingNBT('ragnamod_seven:tertium_seed', '{Souls:10.0d,Type:"mysticalagriculture:zombie"}', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:zombie_seeds', 100)
    seedCraftingNBT('ragnamod_seven:tertium_seed', '{Souls:10.0d,Type:"mysticalagriculture:skeleton"}', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:skeleton_seeds', 100)
    seedCraftingNBT('ragnamod_seven:tertium_seed', '{Souls:6.0d,Type:"mysticalagriculture:basalz"}', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:basalz_seeds', 100)
    seedCraftingNBT('ragnamod_seven:tertium_seed', '{Souls:6.0d,Type:"mysticalagriculture:blitz"}', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:blitz_seeds', 100)
    seedCraftingNBT('ragnamod_seven:tertium_seed', '{Souls:6.0d,Type:"mysticalagriculture:blizz"}', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:blizz_seeds', 100)
    seedCraftingNBT('ragnamod_seven:tertium_seed', '{Souls:6.0d,Type:"mysticalagriculture:rabbit"}', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:rabbit_seeds', 100)
    seedCraftingNBT('ragnamod_seven:tertium_seed', '{Souls:10.0d,Type:"mysticalagriculture:spider"}', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:spider_seeds', 100)
    seedCraftingNBT('ragnamod_seven:tertium_seed', '{Souls:10.0d,Type:"mysticalagriculture:creeper"}', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:creeper_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'evilcraft:dark_gem', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:dark_gem_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:cyber_steel_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:cyber_steel_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:crusteel_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:crusteel_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'undergarden:cloggrum_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:cloggrum_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'thermal:cinnabar', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:cinnabar_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:chorus_metal_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:chorus_metal_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:blazing_copper_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:blazing_copper_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:baolian_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:baolian_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'blue_skies:aquite', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:aquite_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'warden_and_sculk:sculk_block', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:sculk_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:red_beryl_gem', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:red_beryl_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:qivium_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:qivium_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'blue_skies:pyrope_gem', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:pyrope_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'industrialforegoing:plastic', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:plastic_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:piroot_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:piroot_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:magma_steel_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:magma_steel_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:lavium_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:lavium_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:kepu_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:kepu_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:hureaulite_gem', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:hureaulite_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'blue_skies:horizonite_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:horizonite_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:gelot_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:gelot_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:gausum_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:gausum_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:galu_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:galu_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'undergarden:froststeel_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:froststeel_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'undergarden:forgotten_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:forgotten_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'redstone_arsenal:flux_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:flux_infused_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:felsteel_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:felsteel_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'blue_skies:falsite_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:falsite_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'materialis:fairy_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:fairy_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:epidote_gem', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:epidote_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'ftbic:energy_crystal', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:energy_crystal_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'byg:emeraldite_shards', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:emeraldite_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:electrical_copper_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:electrical_copper_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:durasteel_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:durasteel_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:duralumin_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:duralium_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'thermal_extra:dragonsteel_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:dragonsteel_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'ars_nouveau:source_gem', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:source_gem_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'blue_skies:ventium_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:ventium_seeds', 100)
    seedCrafting('ragnamod_seven:tertium_seed', 'tinkers_reforged:wavy_ingot', 'mysticalagriculture:tertium_essence', 'mysticalagriculture:wavy_seeds', 100)
    //Imperium
    seedCrafting('ragnamod_seven:imperium_seed', 'thermal:nickel_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:nickel_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'beyond_earth:steel_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:steel_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'create:experience_nugget', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:experience_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'mysticalagriculture:end_agglomeratio', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:end_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'minecraft:lapis_lazuli', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:lapis_lazuli_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'minecraft:gold_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:gold_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'powah:crystal_blazing', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:blazing_crystal_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'powah:steel_energized', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:energized_steel_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'ae2:fluix_crystal', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:fluix_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'pneumaticcraft:ingot_iron_compressed', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:compressed_iron_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'twilightforest:fiery_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:fiery_ingot_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'twilightforest:knightmetal_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:knightmetal_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'mekanism:ingot_refined_obsidian', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:refined_obsidian_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'mekanism:ingot_refined_glowstone', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:refined_glowstone_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'mekanism:fluorite_gem', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:fluorite_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'mekanism:ingot_osmium', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:osmium_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'botania:elementium_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:elementium_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'tconstruct:rose_gold_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:rose_gold_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'tconstruct:cobalt_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:cobalt_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'immersiveengineering:ingot_hop_graphite', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:hop_graphite_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'thermal:lumium_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:lumium_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'thermal:signalum_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:signalum_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'mekanism:ingot_uranium', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:uranium_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'thermal:invar_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:invar_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'thermal:electrum_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:electrum_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'thermal:constantan_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:constantan_seeds', 150)
    seedCraftingNBT('ragnamod_seven:imperium_seed', '{Souls:8.0d,Type:"mysticalagriculture:enderman"}', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:enderman_seeds', 150)
    seedCraftingNBT('ragnamod_seven:imperium_seed', '{Souls:4.0d,Type:"mysticalagriculture:ghast"}', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:ghast_seeds', 150)
    seedCraftingNBT('ragnamod_seven:imperium_seed', '{Souls:10.0d,Type:"mysticalagriculture:blaze"}', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:blaze_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'undergarden:regalium_crystal', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:regalium_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'byg:pendorite_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:pendorite_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'beyond_earth:ostrum_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:ostrum_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'blue_skies:diopside_gem', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:diopside_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'beyond_earth:desh_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:desh_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'beyond_earth:calorite_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:calorite_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'forbidden_arcanus:arcane_gold_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:arcane_gold_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'forbidden_arcanus:arcane_crystal', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:arcane_crystal_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'byg:ametrine_gems', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:ametrine_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'thermal_extra:twinite_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:twinite_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'thermal_extra:soul_infused_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:soul_infused_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'thermal_extra:shellite_ingot', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:shellite_seeds', 150)
    seedCrafting('ragnamod_seven:imperium_seed', 'forbidden_arcanus:rune', 'mysticalagriculture:imperium_essence', 'mysticalagriculture:rune_seeds', 150)
    //Supremium
    seedCrafting('ragnamod_seven:supremium_seed', 'tconstruct:hepatizon_ingot', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:hepatizon_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'tconstruct:queens_slime_ingot', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:queens_slime_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'tconstruct:manyullyn_ingot', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:manyullyn_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'thermal:enderium_ingot', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:enderium_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'ftbic:iridium_ingot', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:iridium_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'minecraft:netherite_ingot', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:netherite_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'minecraft:emerald', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:emerald_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'minecraft:diamond', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:diamond_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'powah:uraninite', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:uraninite_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'powah:crystal_spirited', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:spirited_crystal_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'powah:crystal_niotic', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:niotic_crystal_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'draconicevolution:draconium_ingot', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:draconium_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'botania:terrasteel_ingot', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:terrasteel_seeds', 200)
    seedCraftingNBT('ragnamod_seven:supremium_seed', '{Souls:8.0d,Type:"mysticalagriculture:wither_skeleton"}', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:wither_skeleton_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'undergarden:utherium_crystal', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:utheric_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'occultism:iesnium_ingot', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:iesnium_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'bloodmagic:rawdemonite', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:demonite_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'ragnamod_seven:solid_nuclear_waste', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:decay_seeds', 200)
    seedCrafting('ragnamod_seven:supremium_seed', 'blue_skies:charoite', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:charoite_seeds', 200)
    //Insanium
    seedCrafting('ragnamod_seven:supremium_seed', 'powah:capacitor_nitro', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:nitro_crystal_seeds', 300)
    seedCrafting('ragnamod_seven:supremium_seed', 'avaritia:neutronium_block', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:neutronium_seeds', 300)
    seedCrafting('ragnamod_seven:supremium_seed', 'draconicevolution:awakened_draconium_block', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:awakened_draconium_seeds', 300)
    seedCrafting('ragnamod_seven:supremium_seed', 'botania:gaia_ingot', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:gaia_spirit_seeds', 300)
    seedCrafting('ragnamod_seven:supremium_seed', 'minecraft:dragon_egg', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:dragon_egg_seeds', 300)
    seedCrafting('ragnamod_seven:supremium_seed', 'minecraft:nether_star', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:nether_star_seeds', 300)
    seedCrafting('ragnamod_seven:supremium_seed', 'avaritia:infinity_catalyst', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:infinity_seeds', 300)
    seedCrafting('ragnamod_seven:supremium_seed', 'draconicevolution:chaos_shard', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:chaotic_seeds', 300)
    seedCrafting('ragnamod_seven:supremium_seed', 'ragnamod_seven:antimatter_pellet_block', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:antimatter_seeds', 300)
    seedCrafting('ragnamod_seven:supremium_seed', 'mythicbotany:alfsteel_block', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:alfsteel_seeds', 300)

    //Craft
    e.shaped('4x ftbic:rubber', ['AAA'], { A: 'mysticalagriculture:rubber_essence' })
    e.shaped('4x evilcraft:dark_gem', ['AAA'], { A: 'mysticalagriculture:dark_gem_essence' })
    e.shaped('4x tinkers_reforged:cyber_steel_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:cyber_steel_essence' })
    e.shaped('4x tinkers_reforged:crusteel_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:crusteel_essence' })
    e.shaped('4x undergarden:cloggrum_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:cloggrum_essence' })
    e.shaped('4x thermal:cinnabar', ['AAA'], { A: 'mysticalagriculture:cinnabar_essence' })
    e.shaped('4x tinkers_reforged:chorus_metal_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:chorus_metal_essence' })
    e.shaped('4x tinkers_reforged:blazing_copper_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:blazing_copper_essence' })
    e.shaped('4x tinkers_reforged:baolian_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:baolian_essence' })
    e.shaped('4x blue_skies:aquite', ['AAA'], { A: 'mysticalagriculture:aquite_essence' })
    e.shaped('4x warden_and_sculk:sculk_block', ['AAA'], { A: 'mysticalagriculture:sculk_essence' })
    e.shaped('4x tinkers_reforged:red_beryl_gem', ['AAA'], { A: 'mysticalagriculture:red_beryl_essence' })
    e.shaped('4x tinkers_reforged:qivium_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:qivium_essence' })
    e.shaped('4x blue_skies:pyrope_gem', ['AAA'], { A: 'mysticalagriculture:pyrope_essence' })
    e.shaped('4x industrialforegoing:plastic', ['AAA'], { A: 'mysticalagriculture:plastic_essence' })
    e.shaped('4x tinkers_reforged:piroot_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:piroot_essence' })
    e.shaped('4x tinkers_reforged:magma_steel_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:magma_steel_essence' })
    e.shaped('4x tinkers_reforged:lavium_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:lavium_essence' })
    e.shaped('4x tinkers_reforged:kepu_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:kepu_essence' })
    e.shaped('4x tinkers_reforged:hureaulite_gem', ['AAA'], { A: 'mysticalagriculture:hureaulite_essence' })
    e.shaped('4x blue_skies:horizonite_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:horizonite_essence' })
    e.shaped('4x tinkers_reforged:gelot_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:gelot_essence' })
    e.shaped('4x tinkers_reforged:gausum_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:gausum_essence' })
    e.shaped('4x tinkers_reforged:galu_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:galu_essence' })
    e.shaped('4x undergarden:froststeel_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:froststeel_essence' })
    e.shaped('4x undergarden:forgotten_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:forgotten_essence' })
    e.shaped('4x redstone_arsenal:flux_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:flux_infused_essence' })
    e.shaped('4x tinkers_reforged:felsteel_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:felsteel_essence' })
    e.shaped('4x blue_skies:falsite_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:falsite_essence' })
    e.shaped('4x materialis:fairy_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:fairy_essence' })
    e.shaped('4x tinkers_reforged:epidote_gem', ['AAA'], { A: 'mysticalagriculture:epidote_essence' })
    e.shaped('4x ftbic:energy_crystal', ['AAA'], { A: 'mysticalagriculture:energy_crystal_essence' })
    e.shaped('4x byg:emeraldite_shards', ['AAA'], { A: 'mysticalagriculture:emeraldite_essence' })
    e.shaped('4x tinkers_reforged:electrical_copper_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:electrical_copper_essence' })
    e.shaped('4x tinkers_reforged:durasteel_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:durasteel_essence' })
    e.shaped('4x tinkers_reforged:duralumin_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:duralium_essence' })
    e.shaped('4x thermal_extra:dragonsteel_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:dragonsteel_essence' })
    e.shaped('4x ars_nouveau:source_gem', ['AAA'], { A: 'mysticalagriculture:source_gem_essence' })
    e.shaped('4x blue_skies:ventium_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:ventium_essence' })
    e.shaped('4x tinkers_reforged:wavy_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:wavy_essence' })
    e.shaped('4x tinkers_reforged:yokel_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:yokel_essence' })
    e.shaped('4x undergarden:regalium_crystal', ['AAA'], { A: 'mysticalagriculture:regalium_essence' })
    e.shaped('4x byg:pendorite_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:pendorite_essence' })
    e.shaped('4x beyond_earth:ostrum_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:ostrum_essence' })
    e.shaped('4x blue_skies:diopside_gem', ['AAA'], { A: 'mysticalagriculture:diopside_essence' })
    e.shaped('4x beyond_earth:desh_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:desh_essence' })
    e.shaped('4x beyond_earth:calorite_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:calorite_essence' })
    e.shaped('4x forbidden_arcanus:arcane_gold_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:arcane_gold_essence' })
    e.shaped('4x forbidden_arcanus:arcane_crystal', ['AAA'], { A: 'mysticalagriculture:arcane_crystal_essence' })
    e.shaped('4x byg:ametrine_gems', ['AAA'], { A: 'mysticalagriculture:ametrine_essence' })
    e.shaped('4x thermal_extra:twinite_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:twinite_essence' })
    e.shaped('4x thermal_extra:soul_infused_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:soul_infused_essence' })
    e.shaped('4x thermal_extra:shellite_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:shellite_essence' })
    e.shaped('4x forbidden_arcanus:rune', ['AAA'], { A: 'mysticalagriculture:rune_essence' })
    e.shaped('4x undergarden:utherium_crystal', ['AAA'], { A: 'mysticalagriculture:utheric_essence' })
    e.shaped('4x occultism:iesnium_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:iesnium_essence' })
    e.shaped('4x bloodmagic:rawdemonite', ['AAA'], { A: 'mysticalagriculture:demonite_essence' })
    e.shaped('4x ragnamod_seven:solid_nuclear_waste', ['AAA'], { A: 'mysticalagriculture:decay_essence' })
    e.shaped('4x blue_skies:charoite', ['AAA'], { A: 'mysticalagriculture:charoite_essence' })
    e.shaped('avaritia:infinity_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:infinity_essence' })
    e.shaped('3x draconicevolution:medium_chaos_frag', ['AAA'], { A: 'mysticalagriculture:chaotic_essence' })
    e.shaped('mekanism:pellet_antimatter', ['AAA'], { A: 'mysticalagriculture:antimatter_essence' })
    e.shaped('mythicbotany:alfsteel_ingot', ['AAA', 'A A', 'AAA'], { A: 'mysticalagriculture:alfsteel_essence' })

    //GardenCloche
    e.custom({ "type": "immersiveengineering:fertilizer", "growthModifier": 20, "input": { "item": "botania:life_essence" } })
    function mysticalCloche(name, soil) { e.custom({ "type": "immersiveengineering:cloche", "results": [{ "item": "mysticalagriculture:" + name + "_essence", "count": 2 }], "input": { "item": "mysticalagriculture:" + name + "_seeds" }, "soil": { "item": soil }, "time": 200, "render": { "type": "crop", "block": "mysticalagriculture:" + name + "_crop" } }) }

    mysticalCloche("air", 'mysticalagriculture:inferium_farmland')
    mysticalCloche("fire", 'mysticalagriculture:inferium_farmland')
    mysticalCloche("water", 'mysticalagriculture:inferium_farmland')
    mysticalCloche("earth", 'mysticalagriculture:inferium_farmland')
    mysticalCloche("inferium", 'mysticalagriculture:inferium_farmland')
    mysticalCloche("stone", 'mysticalagriculture:inferium_farmland')
    mysticalCloche("dirt", 'mysticalagriculture:inferium_farmland')
    mysticalCloche("wood", 'mysticalagriculture:inferium_farmland')
    mysticalCloche("ice", 'mysticalagriculture:inferium_farmland')
    mysticalCloche("deepslate", 'mysticalagriculture:inferium_farmland')
    mysticalCloche("chicken", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("pig", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("amethyst", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("honey", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("coral", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("coal", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("nether", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("dye", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("nature", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("menril", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("limestone", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("mystical_flower", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("apatite", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("saltpeter", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("aluminum", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("sulfur", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("silicon", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("rubber", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("turtle", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("slime", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("fish", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("squid", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("sheep", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("cow", 'mysticalagriculture:prudentium_farmland')
    mysticalCloche("skeleton", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("zombie", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("prismarine", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("obsidian", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("redstone", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("glowstone", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("nether_quartz", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("copper", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("iron", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("certus_quartz", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("sky_stone", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("ironwood", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("steeleaf", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("manasteel", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("pig_iron", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("slimesteel", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("amethyst_bronze", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("basalz", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("blitz", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("blizz", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("lead", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("silver", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("brass", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("zinc", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("bronze", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("tin", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("rabbit", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("spider", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("creeper", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("dark_gem", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("cyber_steel", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("crusteel", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("cloggrum", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("cinnabar", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("chorus_metal", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("blazing_copper", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("baolian", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("aquite", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("sculk", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("red_beryl", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("qivium", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("pyrope", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("plastic", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("piroot", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("magma_steel", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("lavium", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("kepu", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("hureaulite", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("horizonite", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("gelot", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("gausum", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("galu", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("froststeel", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("forgotten", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("flux_infused", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("felsteel", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("falsite", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("fairy", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("epidote", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("energy_crystal", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("emeraldite", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("electrical_copper", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("durasteel", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("duralium", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("dragonsteel", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("yokel", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("wavy", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("ventium", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("source_gem", 'mysticalagriculture:tertium_farmland')
    mysticalCloche("nickel", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("steel", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("enderman", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("ghast", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("blaze", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("experience", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("end", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("lapis_lazuli", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("gold", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("blazing_crystal", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("energized_steel", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("fluix", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("compressed_iron", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("fiery_ingot", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("knightmetal", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("refined_obsidian", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("refined_glowstone", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("fluorite", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("osmium", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("elementium", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("rose_gold", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("cobalt", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("hop_graphite", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("lumium", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("signalum", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("uranium", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("invar", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("electrum", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("constantan", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("regalium", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("pendorite", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("ostrum", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("diopside", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("desh", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("calorite", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("arcane_gold", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("arcane_crystal", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("ametrine", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("twinite", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("soul_infused", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("shellite", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("rune", 'mysticalagriculture:imperium_farmland')
    mysticalCloche("hepatizon", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("queens_slime", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("manyullyn", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("enderium", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("iridium", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("wither_skeleton", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("netherite", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("emerald", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("diamond", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("uraninite", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("spirited_crystal", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("niotic_crystal", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("draconium", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("terrasteel", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("utheric", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("iesnium", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("demonite", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("decay", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("charoite", 'mysticalagriculture:supremium_farmland')
    mysticalCloche("chaotic", 'ragnamod_seven:chaotic_crux')
    mysticalCloche("antimatter", 'ragnamod_seven:antimatter_crux')
    mysticalCloche("alfsteel", 'ragnamod_seven:alfsteel_crux')
    mysticalCloche("nitro_crystal", 'mysticalagradditions:nitro_crystal_crux')
    mysticalCloche("neutronium", 'mysticalagradditions:neutronium_crux')
    mysticalCloche("awakened_draconium", 'mysticalagradditions:awakened_draconium_crux')
    mysticalCloche("gaia_spirit", 'mysticalagradditions:gaia_spirit_crux')
    mysticalCloche("dragon_egg", 'mysticalagradditions:dragon_egg_crux')
    mysticalCloche("nether_star", 'mysticalagradditions:nether_star_crux')
    mysticalCloche("infinity", 'ragnamod_seven:infinity_crux')

})