onEvent('fluid.registry', e => {
    e.create('ragnamod_seven:aureal')
        .thinTexture(0xa19fc9)
        .bucketColor(0xa19fc9)
        .displayName('Aureal')

    e.create('ichor')
        .displayName('Ichor')
        .stillTexture('tconstruct:fluid/ichor_still')
        .flowingTexture('tconstruct:fluid/ichor_flowing')
        .bucketColor(0xcc4100)

    e.create('chaos_liquid')
        .displayName('Chaos Liquid')
        .stillTexture('ragnamod_seven:fluid/chaos_still')
        .flowingTexture('ragnamod_seven:fluid/chaos_flowing')
        .bucketColor(0x0d0d0d)

    //Skyblock
    e.create('cake_batter')
        .displayName('Cake Batter')
        .stillTexture('ragnamod_seven:fluid/cake_batter/still')
        .flowingTexture('ragnamod_seven:fluid/cake_batter/flow')
        .bucketColor(0xd9bb8c)

    e.create('ender_cake_batter')
        .displayName('Ender Cake Batter')
        .stillTexture('ragnamod_seven:fluid/ender_cake_batter/still')
        .flowingTexture('ragnamod_seven:fluid/ender_cake_batter/flow')
        .bucketColor(0x7f6497)

    e.create('earth_cake_batter')
        .displayName('Earth Cake Batter')
        .stillTexture('ragnamod_seven:fluid/earth_cake_batter/still')
        .flowingTexture('ragnamod_seven:fluid/earth_cake_batter/flow')
        .bucketColor(0x5a8356)

    e.create('sky_cake_batter')
        .displayName('Sky Cake Batter')
        .stillTexture('ragnamod_seven:fluid/sky_cake_batter/still')
        .flowingTexture('ragnamod_seven:fluid/sky_cake_batter/flow')
        .bucketColor(0x537f7f)

    e.create('blood_cake_batter')
        .displayName('Blood Cake Batter')
        .stillTexture('ragnamod_seven:fluid/blood_cake_batter/still')
        .flowingTexture('ragnamod_seven:fluid/blood_cake_batter/flow')
        .bucketColor(0xaa0707)

    e.create('magma_cake_batter')
        .displayName('Magma Cake Batter')
        .stillTexture('ragnamod_seven:fluid/magma_cake_batter/still')
        .flowingTexture('ragnamod_seven:fluid/magma_cake_batter/flow')
        .bucketColor(0x752501)

    e.create('nether_cake_batter')
        .displayName('Nether Cake Batter')
        .stillTexture('ragnamod_seven:fluid/nether_cake_batter/still')
        .flowingTexture('ragnamod_seven:fluid/nether_cake_batter/flow')
        .bucketColor(0x574338)

    e.create('end_cake_batter')
        .displayName('End Cake Batter')
        .stillTexture('ragnamod_seven:fluid/end_cake_batter/still')
        .flowingTexture('ragnamod_seven:fluid/end_cake_batter/flow')
        .bucketColor(0x3b3151)

    e.create('overworld_cake_batter')
        .displayName('Overworld Cake Batter')
        .stillTexture('ragnamod_seven:fluid/overworld_cake_batter/still')
        .flowingTexture('ragnamod_seven:fluid/overworld_cake_batter/flow')
        .bucketColor(0x926947)

    e.create('twilight_cake_batter')
        .displayName('Twilight Cake Batter')
        .stillTexture('ragnamod_seven:fluid/twilight_cake_batter/still')
        .flowingTexture('ragnamod_seven:fluid/twilight_cake_batter/flow')
        .bucketColor(0x6e4523)

    e.create('mining_cake_batter')
        .displayName('Mining Cake Batter')
        .stillTexture('ragnamod_seven:fluid/mining_cake_batter/still')
        .flowingTexture('ragnamod_seven:fluid/mining_cake_batter/flow')
        .bucketColor(0x5a9c99)

    e.create('undergarden_cake_batter')
        .displayName('Undergarden Cake Batter')
        .stillTexture('ragnamod_seven:fluid/undergarden_cake_batter/still')
        .flowingTexture('ragnamod_seven:fluid/undergarden_cake_batter/flow')
        .bucketColor(0x46663a)

    e.create('egg_yolk')
        .displayName('Egg Yolk')
        .stillTexture('ragnamod_seven:fluid/egg_yolk_still')
        .flowingTexture('ragnamod_seven:fluid/egg_yolk_flow')
        .bucketColor(0xf6c68d)

    e.create('overworld_icing')
        .displayName('§2Overworld Icing')
        .stillTexture('ragnamod_seven:fluid/overworld_icing/still')
        .flowingTexture('ragnamod_seven:fluid/overworld_icing/flowing')
        .bucketColor(0x70a556)

    e.create('undergarden_icing')
        .displayName('§5Undergarden Icing')
        .stillTexture('ragnamod_seven:fluid/undergarden_icing/still')
        .flowingTexture('ragnamod_seven:fluid/undergarden_icing/flowing')
        .bucketColor(0x340042)

    e.create('end_icing')
        .displayName('§eEnd Icing')
        .stillTexture('ragnamod_seven:fluid/end_icing/still')
        .flowingTexture('ragnamod_seven:fluid/end_icing/flowing')
        .bucketColor(0xe9e888)

    e.create('nether_icing')
        .displayName('§4Nether Icing')
        .stillTexture('ragnamod_seven:fluid/nether_icing/still')
        .flowingTexture('ragnamod_seven:fluid/nether_icing/flowing')
        .bucketColor(0xae1000)

    e.create('overworld_essence')
        .displayName('Overworld Essence')
        .stillTexture('ragnamod_seven:fluid/overworld_essence/still')
        .flowingTexture('ragnamod_seven:fluid/overworld_essence/flowing')
        .bucketColor(0x6abb56)

    e.create('end_essence')
        .displayName('End Essence')
        .stillTexture('ragnamod_seven:fluid/end_essence/still')
        .flowingTexture('ragnamod_seven:fluid/end_essence/flowing')
        .bucketColor(0x424242)

    e.create('nether_essence')
        .displayName('Nether Essence')
        .stillTexture('ragnamod_seven:fluid/nether_essence/still')
        .flowingTexture('ragnamod_seven:fluid/nether_essence/flowing')
        .bucketColor(0xdc4234)

    e.create('distilled_water')
        .displayName('Distilled Water')
        .thinTexture(0x5cb8d5)
        .bucketColor(0x5cb8d5)
        .bucketColor(0x5cb8d5)

    e.create('prosperity_fluid')
        .displayName('Liquid Prosperity')
        .thinTexture(0xaecccc)
        .bucketColor(0xaecccc)
        .bucketColor(0xaecccc)
})