onEvent('item.registry', e => {

    e.create('ragnamod_seven:portal_activator').displayName('Portal Activator').maxStackSize(1)
    e.create('chickens:smashed_chicken').displayName('Smashed Chicken')
    e.create('chickens:chicken_skin').displayName('Chicken Skin')
    e.create('chickens:chicken_shell').displayName('Chicken Shell')
    e.create('chickens:nether_star_shard').displayName('§eNether Star Shard').glow(true)
    e.create('chickens:soul_chicken').displayName('Chicken Soul').glow(true)
    e.create('chickens:soul_bee').displayName('Bee Soul').glow(true)
    e.create('chemlib:draconium_compound').displayName('Draconium Compound')
    e.create('ragnamod_seven:infinity_nugget').displayName('§cInfinity Nugget')
    e.create('ragnamod_seven:infinity_shard').displayName('§cInfinity Shard')
    e.create('ragnamod_seven:infinity_gem').displayName('§cInfinity Gem')
    e.create('ragnamod_seven:infinity_gear').displayName('§cInfinity Gear')
    e.create('ragnamod_seven:sphere').displayName('Sphere Of All Things')
    e.create('ragnamod_seven:ignis_soul').displayName('Ignis Soul')
    e.create('ragnamod_seven:revenant_soul').displayName('Revanant Soul')
    e.create('ragnamod_seven:netherite_monstrosity_soul').displayName('Netherite Monstrosity Soul')
    e.create('ragnamod_seven:ender_golem_soul').displayName('Ender Golem Soul')
    e.create('ragnamod_seven:ender_guardian_soul').displayName('Ender Guardian Soul')
    e.create('ragnamod_seven:log_egg_component').displayName('Log Egg Component')
    e.create('gateways:catalyst_small_pearl_gate').displayName('Small Gate Catalyst')
    e.create('gateways:catalyst_medium_pearl_gate').displayName('Medium Gate Catalyst')
    e.create('gateways:catalyst_large_pearl_gate').displayName('Large Gate Catalyst')
    e.create('solarflux:photovoltaic_cell_7').displayName('Photovoltaic Cell VII')
    e.create('solarflux:photovoltaic_cell_8').displayName('Photovoltaic Cell VIII')
    e.create('solarflux:photovoltaic_cell_9').displayName('Photovoltaic Cell IX')
    e.create('solarflux:photovoltaic_cell_10').displayName('Photovoltaic Cell X')
    e.create('solarflux:photovoltaic_cell_11').displayName('Photovoltaic Cell XI')
    e.create('solarflux:photovoltaic_cell_12').displayName('Photovoltaic Cell XII')
    e.create('solarflux:photovoltaic_cell_13').displayName('Photovoltaic Cell XIII')
    e.create('hostilenetworks:blueskies_prediction').displayName('Generalized Blue Skies Prediction')
    e.create('hostilenetworks:undergarden_prediction').displayName('Generalized Undergarden Prediction')
    e.create('hostilenetworks:polymer_clay').displayName('Polymer Clay')
    e.create('ragnamod_seven:war_essence').displayName('War Essence')
    e.create('ragnamod_seven:famine_essence').displayName('Famine Essence')
    e.create('ragnamod_seven:death_essence').displayName('Death Essence')
    e.create('ragnamod_seven:conquest_essence').displayName('Conquest Essence')
    e.create('ragnamod_seven:war_essence_materialized').displayName('Materialized War Essence')
    e.create('ragnamod_seven:famine_essence_materialized').displayName('Materialized Famine Essence')
    e.create('ragnamod_seven:death_essence_materialized').displayName('Materialized Death Essence')
    e.create('ragnamod_seven:conquest_essence_materialized').displayName('Materialized Conquest Essence')
    e.create('ragnamod_seven:war_ingot').displayName('War Ingot')
    e.create('ragnamod_seven:famine_ingot').displayName('Famine Ingot')
    e.create('ragnamod_seven:death_ingot').displayName('Death Ingot')
    e.create('ragnamod_seven:conquest_ingot').displayName('Conquest Ingot')
    e.create('ragnamod_seven:war_nugget').displayName('War Nugget')
    e.create('ragnamod_seven:famine_nugget').displayName('Famine Nugget')
    e.create('ragnamod_seven:death_nugget').displayName('Death Nugget')
    e.create('ragnamod_seven:conquest_nugget').displayName('Conquest Nugget')
    e.create('ragnamod_seven:sculk_ingot').displayName('Sculk Ingot')
    e.create('ragnamod_seven:shub_niggurath_ingot').displayName('Shub Niggurath Ingot')
    e.create('ragnamod_seven:unknown_ingot').displayName('Unknown Ingot')
    e.create('ragnamod_seven:unknown_nugget').displayName('Unknown Nugget')
    e.create('ragnamod_seven:raw_unknown').displayName('Raw Unknown')
    e.create('ragnamod_seven:chemical_core').displayName('Chemical Core').glow(true)
    e.create('ragnamod_seven:ghast_cow_tear').displayName('Ghast Cow Tear')
    e.create('ragnamod_seven:ghast_cow_star').displayName('Ghast Cow Star').glow(true)
    e.create('ragnamod_seven:chemical_draconium_ingot').displayName('Chemical Draconium Ingot')
    e.create('ragnamod_seven:chemical_draconium_nugget').displayName('Chemical Draconium Nugget')
    e.create('ragnamod_seven:condensed_ingot').displayName('Condensed Ingot')
    e.create('ragnamod_seven:black_sphere').displayName('Not an Item').maxStackSize(1)
    e.create('miniutilities:stable_ingot').displayName('Stable Ingot')
    e.create('ragnamod_seven:agglomerate_matter_minecraft1').displayName('§bMinecraft\'s Agglomerate Matter #1')
    e.create('ragnamod_seven:agglomerate_matter_minecraft2').displayName('§bMinecraft\'s Agglomerate Matter #2')
    e.create('ragnamod_seven:agglomerate_matter_minecraft3').displayName('§bMinecraft\'s Agglomerate Matter #3')
    e.create('ragnamod_seven:agglomerate_matter_twilight').displayName('§bTwilight\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_blood_magic').displayName('§bBlood Magic\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_create').displayName('§bCreate\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_mekanism').displayName('§bMekanism\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_powah').displayName('§bPowah\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_botania').displayName('§bBotania\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_blue_skies').displayName('§bBlue Skies\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_space').displayName('§bSpace\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_blocky').displayName('§bBlocky\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_mobs').displayName('§bMobs\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_psi').displayName('§bPSI\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_thermal').displayName('§bThermal\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_evil_craft').displayName('§bEvil Craft\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_ae2').displayName('§bApplied Energistics\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_forbidden_arcanus').displayName('§bForbidden and Arcanus\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_undergarden').displayName('§bUndergarden\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_ftbic').displayName('§bFTBIC\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_tconstruct').displayName('§bTinkers Construct\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_ars').displayName('§bArs Nouveau\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_pneumaticcraft').displayName('§bPneumaticcraft\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_tech').displayName('§bTech\'s Agglomerate Matter')
    e.create('ragnamod_seven:creative_augment_base').displayName('Creative Augmente Base')
    e.create('ragnamod_seven:holy_powders').displayName('Holy Magic Powders')
    e.create('ragnamod_seven:creative_tc_crystal').displayName("Creative Tinkers' Crystal").glow(true).maxStackSize(1)
    e.create('ragnamod_seven:alloy_matrix').displayName("§cMatrix Alloy").glow(true).maxStackSize(1)
    e.create('ragnamod_seven:solid_nuclear_waste').displayName("Solid Nuclear Waste")
    e.create('ragnamod_seven:bloody_addon').displayName("Bloody Addon").maxStackSize(4)
    e.create('ragnamod_seven:blood_data_model').displayName("Blood Data Model").maxStackSize(1)
    e.create('ragnamod_seven:blood_infused_data_model').displayName("Blood Infused Data Model").maxStackSize(1)
    e.create('ragnamod_seven:deeply_blood_infused_data_model').displayName("Deeply Blood Infused Data Model").maxStackSize(1)
    e.create('ragnamod_seven:speed_addon').displayName("Speed Addon").maxStackSize(8)
    e.create('ragnamod_seven:chaos_dust').displayName("Chaos Dust")
    e.create('ragnamod_seven:unpredictable_dust').displayName("Unpredictable Dust").glow(true)
    e.create('ragnamod_seven:questionable_mixture').displayName("Questionable Mixture")
    e.create('ragnamod_seven:strange_mixture').displayName("Strange Mixture")
    e.create('ragnamod_seven:sickening_mixture').displayName("Sickening Mixture")
    e.create('thermal:press_rod_die').displayName("Rodworking Die").maxStackSize(1)
    e.create('thermal:press_wire_die').displayName("Wireworking Die").maxStackSize(1)
    e.create('bloodmagic:dawnscribetool').displayName("Inscription Tool: Dawn").maxStackSize(1).maxDamage(40)
    e.create('ragnamod_seven:purple_gem').displayName("§dPurple Gem").maxStackSize(1).glow(true)
    e.create('ragnamod_seven:blue_gem').displayName("§9Blue Gem").maxStackSize(1).glow(true)
    e.create('ragnamod_seven:cyan_gem').displayName("§3Cyan Gem").maxStackSize(1).glow(true)
    e.create('ragnamod_seven:green_gem').displayName("§2Green Gem").maxStackSize(1).glow(true)
    e.create('ragnamod_seven:yellow_gem').displayName("§6Yellow Gem").maxStackSize(1).glow(true)
    e.create('ragnamod_seven:red_gem').displayName("§cRed Gem").maxStackSize(1).glow(true)
    e.create('ragnamod_seven:white_gem').displayName("§fWhite Gem").maxStackSize(1).glow(true)
    //Skyblock
    e.create('ragnamod_seven:blackstone_pebble')
    e.create('ragnamod_seven:andesite_pebble')
    e.create('ragnamod_seven:tuff_pebble')
    e.create('ragnamod_seven:granite_pebble')
    e.create('ragnamod_seven:dripstone_pebble')
    e.create('ragnamod_seven:diorite_pebble')
    e.create('ragnamod_seven:stone_pebble')
    e.create('ragnamod_seven:calcite_pebble')
    e.create('ragnamod_seven:basalt_pebble')
    e.create('ragnamod_seven:deepslate_pebble')
    e.create('ragnamod_seven:powdered_dirt')
    e.create('ragnamod_seven:acacia_seed')
    e.create('ragnamod_seven:birch_seed')
    e.create('ragnamod_seven:runewood_seed')
    e.create('ragnamod_seven:dark_oak_seed')
    e.create('ragnamod_seven:jungle_seed')
    e.create('ragnamod_seven:oak_seed')
    e.create('ragnamod_seven:spruce_seed')
    e.create('ragnamod_seven:kelp_seed')
    e.create('ragnamod_seven:pickle_seed')
    e.create('ragnamod_seven:bamboo_seeds')
    e.create('ragnamod_seven:cactus_seeds')
    e.create('ragnamod_seven:carrot_seeds')
    e.create('ragnamod_seven:potato_seeds')
    e.create('ragnamod_seven:sugarcane_seeds')
    e.create('ragnamod_seven:grass_seeds')
    e.create('ragnamod_seven:stone_alloy')
    e.create('ragnamod_seven:incomplete_catalyst')
    e.create('ragnamod_seven:red_antimatter_pellet')
    e.create('ragnamod_seven:blue_antimatter_pellet')
    e.create('ragnamod_seven:green_antimatter_pellet')
    e.create('ragnamod_seven:vivid_opinium_core')
    //cake
    function cake(name) {
        e.create('ragnamod_seven:' + name + '_cake_mold_filled').maxStackSize(1)
        e.create('ragnamod_seven:' + name + '_cake_mold_baked').maxStackSize(1)
        e.create('ragnamod_seven:' + name + '_cake_base_baked')
    }
    var nameofcake = [
        'ender', 'earth', 'sky', 'blood', 'magma', 'nether', 'end', 'overworld', 'twilight', 'city', 'undergarden', 'mining'
    ]
    nameofcake.forEach(C => { cake(C) })
    e.create('ragnamod_seven:cake_mold').maxStackSize(1)
    e.create('ragnamod_seven:cake_mold_filled').maxStackSize(1)
    e.create('ragnamod_seven:cake_mold_baked').maxStackSize(1)
    e.create('ragnamod_seven:egg_shell')
    //FTP
    e.create('ragnamod_seven:ftp').maxStackSize(1).displayName("§9F§2T§4P")
    e.create('ragnamod_seven:f').maxStackSize(1).displayName("§9F")
    e.create('ragnamod_seven:t').maxStackSize(1).displayName("§2T")
    e.create('ragnamod_seven:p').maxStackSize(1).displayName("§4P")

    //Tiny Agglomerate
    e.create('ragnamod_seven:tiny_agglomerate_matter_minecraft1').displayName('§bTiny Minecraft\'s Agglomerate Matter #1')
    e.create('ragnamod_seven:tiny_agglomerate_matter_minecraft2').displayName('§bTiny Minecraft\'s Agglomerate Matter #2')
    e.create('ragnamod_seven:tiny_agglomerate_matter_minecraft3').displayName('§bTiny Minecraft\'s Agglomerate Matter #3')
    e.create('ragnamod_seven:tiny_agglomerate_matter_twilight').displayName('§bTiny Twilight\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_blood_magic').displayName('§bTiny Blood Magic\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_create').displayName('§bTiny Create\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_mekanism').displayName('§bTiny Mekanism\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_powah').displayName('§bTiny Powah\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_botania').displayName('§bTiny Botania\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_blue_skies').displayName('§bTiny Blue Skies\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_space').displayName('§bTiny Space\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_blocky').displayName('§bTiny Blocky\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_mobs').displayName('§bTiny Mobs\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_psi').displayName('§bTiny PSI\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_thermal').displayName('§bTiny Thermal\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_evil_craft').displayName('§bTiny Evil Craft\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_ae2').displayName('§bTiny Applied Energistics\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_forbidden_arcanus').displayName('§bTiny Forbidden and Arcanus\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_undergarden').displayName('§bTiny Undergarden\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_ftbic').displayName('§bTiny FTBIC\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_tconstruct').displayName('§bTiny Tinkers Construct\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_ars').displayName('§bTiny Ars Nouveau\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_pneumaticcraft').displayName('§bTiny Pneumaticcraft\'s Agglomerate Matter')
    e.create('ragnamod_seven:tiny_agglomerate_matter_tech').displayName('§bTiny Tech\'s Agglomerate Matter')
    e.create('ragnamod_seven:blue_gem_show').displayName("§9Blue Gem").maxStackSize(1)
    e.create('ragnamod_seven:green_gem_show').displayName("§2Green Gem").maxStackSize(1)
    e.create('ragnamod_seven:red_gem_show').displayName("§cRed Gem").maxStackSize(1)
    e.create('ragnamod_seven:overworld_essence').maxStackSize(1)
    e.create('ragnamod_seven:nether_essence').maxStackSize(1)
    e.create('ragnamod_seven:end_essence').maxStackSize(1)
    e.create('ragnamod_seven:inferium_seed').displayName('§eInferium Seed Base')
    e.create('ragnamod_seven:prudentium_seed').displayName('§2Prudentium Seed Base')
    e.create('ragnamod_seven:tertium_seed').displayName('§6Tertium Seed Base')
    e.create('ragnamod_seven:imperium_seed').displayName('§9Imperium Seed Base')
    e.create('ragnamod_seven:supremium_seed').displayName('§cSupremium Seed Base')
    e.create('ragnamod_seven:insanium_seed').displayName('§5Insanium Seed Base')
    e.create('ragnamod_seven:prosperity_dust').displayName('Prosperity Dust')
    e.create('ragnamod_seven:inferium_dust_speck').displayName('Inferium Dust Speck')
    e.create('ragnamod_seven:prudentium_dust_speck').displayName('Prudentium Dust Speck')
    e.create('ragnamod_seven:tertium_dust_speck').displayName('Tertium Dust Speck')
    e.create('ragnamod_seven:imperium_dust_speck').displayName('Imperium Dust Speck')
    e.create('ragnamod_seven:supremium_dust_speck').displayName('Supremium Dust Speck')
    e.create('ragnamod_seven:insanium_dust_speck').displayName('Insanium Dust Speck')
})